[package]
name = "clique"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.7.1"
rayon = "1.10.0"
rstest = "0.25.0"
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }

[profile.test]
opt-level = 3
debug = false

